### ISSUE TITLE
Duration in bulk-register is not working when there is only one issue

### ISSUE THREAD

**Issue by kaerimichi** [kaerimichi/jira-worklog-manager#13]
Given the work log example:
```
summary:
  - date: 25/11
    worklogs:
      - issueId: EXAMPLE
        duration: 50
```
When I run `bulk-register` it gives me the error:
```
Cannot read property 'split' of null
```
