### ISSUE TITLE
Add a list of tasks with aliases

### ISSUE THREAD

**Issue by kaerimichi** [kaerimichi/jira-worklog-manager#5]
It would be useful to have a list on the YAML file to store aliases that can be referenced in the summary:

```
tasks:
- issueId: ABCDE-1234
  alias: MY_ALIAS
summary:
- date: 10/10
  worklogs:
  - issueId: MY_ALIAS
    start: 00h00
    end: 00h00
```
