### ISSUE TITLE
Duration instead of start/end not working

### ISSUE THREAD

**Issue by kaerimichi** [kaerimichi/jira-worklog-manager#6]
When you set only the duration (in bulk mode), the work log is not registered.

```
- date: 11/08
  worklogs:
  - issueId: ABCDE-0101
    duration: 35
```
